server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    # Redirect all other traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name daim-lab.com www.daim-lab.com;

    include /etc/nginx/snippets/ssl.conf;

    location / {
        root /var/www/daim-lab.com;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

include /etc/nginx/subdomains/*.conf;
